Traceback (most recent call last):
  File "/home/sagemaker-user/SP/server.py", line 8, in <module>
    from flask_ngrok import run_with_ngrok 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'flask_ngrok'
Traceback (most recent call last):
  File "/home/sagemaker-user/SP/server.py", line 8, in <module>
    from flask_ngrok import run_with_ngrok 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'flask_ngrok'
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://169.255.255.2:5000
Press CTRL+C to quit
[2025-03-20 06:24:00,922] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagemaker-user/SP/server.py", line 16, in chart
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
127.0.0.1 - - [20/Mar/2025 06:24:00] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [20/Mar/2025 06:24:01] "GET /favicon.ico HTTP/1.1" 404 -
 * Serving Flask app 'server'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-03-20 06:32:25,396] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagemaker-user/SP/server.py", line 16, in chart
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
127.0.0.1 - - [20/Mar/2025 06:32:25] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [20/Mar/2025 06:32:26] "GET /favicon.ico HTTP/1.1" 404 -
 * Serving Flask app 'server'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-03-20 06:36:09,847] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagemaker-user/SP/server.py", line 16, in chart
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
127.0.0.1 - - [20/Mar/2025 06:36:09] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [20/Mar/2025 06:36:10] "GET /favicon.ico HTTP/1.1" 404 -
[2025-03-20 06:38:41,802] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagemaker-user/SP/server.py", line 16, in chart
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
127.0.0.1 - - [20/Mar/2025 06:38:41] "GET / HTTP/1.1" 500 -
 * Serving Flask app 'server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://169.255.255.2:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-786-318
127.0.0.1 - - [20/Mar/2025 06:39:57] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2025 06:39:58] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/home/sagemaker-user/SP/server.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-786-318
 * Serving Flask app 'server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://169.255.255.2:5001
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-786-318
127.0.0.1 - - [20/Mar/2025 06:40:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2025 06:40:48] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/home/sagemaker-user/SP/server.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-786-318
 * Serving Flask app 'server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://169.255.255.2:5002
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-786-318
127.0.0.1 - - [20/Mar/2025 06:41:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2025 06:41:41] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/home/sagemaker-user/SP/server.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-786-318
 * Serving Flask app 'server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://169.255.255.2:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 215-786-318
127.0.0.1 - - [20/Mar/2025 06:43:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2025 06:43:01] "GET /favicon.ico HTTP/1.1" 404 -
